### ISSUE TITLE
serde tag attribute bug

### ISSUE THREAD

**Issue by yoghurt-x86** [Heliozoa/elm_rs#2]
I was playing around with this when i noticed a small bug in the elm code that's generated:

Here's a type that i use in my project:
![image](https://user-images.githubusercontent.com/25183723/208887014-032a7cb8-1897-405d-a776-299e53198bc3.png)

If i add this serde tag, the resulting elm code doesn't have correct indentation and stops compiling. 
![image](https://user-images.githubusercontent.com/25183723/208887230-6ef04af1-77a8-43b1-bc1a-d21ac6ae1c94.png)

The result:
![image](https://user-images.githubusercontent.com/25183723/208887600-cd6a838c-54ff-4694-8348-9fcde17d0f97.png)

It's a small bug, and I ended up removing the serde attribute after i had replaced all my old decoders with the ones generated with elm_rs.

**Comment by Heliozoa** [comment]
Hi,
Thanks for posting the issue! I just published `0.2.1` where the bug is fixed.

There were a couple of places where I hadn't added enough indentation and the tests didn't catch it because it only caused problems with more than one struct-type enum variant and my tests only had one in each enum.
